version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: raven-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: boss123
      MYSQL_DATABASE: employee_db
      MYSQL_USER: raven
      MYSQL_PASSWORD: raven123
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data: