version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: raven-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: boss123
      MYSQL_DATABASE: employee_db
      MYSQL_USER: raven
      MYSQL_PASSWORD: raven123
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  employee-api:
    build: .
    container_name: ms-employee-app
    ports:
      - "8080:8080"
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/employee_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=raven
      - SPRING_DATASOURCE_PASSWORD=raven123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

volumes:
  mysql_data: