spring:
  profiles:
    active: dev
  jackson:
    deserialization:
      accept-single-value-as-array: true

#Health Checks
management:
  endpoints:
    web:
      exposure:
        include: health,info

#Nivel base para toda la app
logging:
  level:
    root: INFO
    # Silenciar hibernate
    org.hibernate: ERROR
    # Normal en paquetes
    com.jbe.msemployee: INFO